[tools]
bun = "1.3.5"
npm = "11.6.3"

[env]
_.path = [
    "{{config_root}}/node_modules/.bin",
]

[tasks.setup]
run = "bun install"

[tasks.build]
run = "bun run build"

[tasks.publish]
run = "npm publish"